# Generated by Django 3.0.7 on 2020-06-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(),
        ),
    ]
